apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: helsesjekker
  namespace: sikkerhetstjenesten
spec:
  interval: 60s
  module: http_2xx
  prober:
    path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
    url: alloy.nais-system:12345
  targets:
    staticConfig:
      static:
      - http://entra-proxy.sikkerhetstjenesten/monitoring/health/graph
      - http://entra-proxy.sikkerhetstjenesten/monitoring/health/valKey
      - http://entra-proxy.sikkerhetstjenesten/monitoring/health/norg

