apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: entraproxy-probe-alerts
    namespace: sikkerhetstjenesten
    labels:
      team: sikkerhetstjenesten
spec:
  groups:
    - name: probe-errors
      rules:
        - alert: HelsesjekkValKeyFeilet
          expr: up{instance="http://entra-proxy.sikkerhetstjenesten/monitoring/health/valkey", namespace="sikkerhetstjenesten"} == 0
          for: 2m
          annotations:
            consequence: Valkey er nede
            action: "Sjekk Grafana og Kibana"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/goto/Ejqy8DzDg?orgId=1
              Loki securelogs: 
              Kibana åpne logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/vLl8e
          labels:
            namespace: sikkerhetstjenesten
            severity: critical
        - alert: HelsesjekkEntraFeilet
          expr: up{instance="http://entra-proxy.sikkerhetstjenesten/monitoring/health/graph", namespace="tilgangsmaskin"} == 0
          for: 2m
          annotations:
            consequence: Entra er nede
            action: "Sjekk Grafana og Kibana"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/goto/Ejqy8DzDg?orgId=1
              Loki securelogs: 
              Kibana åpne logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/vLl8e
          labels:
            namespace: sikkerhetstjenesten
            severity: critical
        - alert: HelsesjekkNorgFeilet
          expr: up{instance="http://entra-proxy.sikkerhetstjenesten/monitoring/health/norg", namespace="tilgangsmaskin"} == 0
          for: 2m
          annotations:
            consequence: Norg2 er nede
            action: "Sjekk Grafana og Kibana"
            summary: |-
              Grafana: https://grafana.nav.cloud.nais.io/goto/Ejqy8DzDg?orgId=1
              Loki securelogs: 
              Kibana åpne logger: https://logs.adeo.no/s/nav-logs-legacy/app/r/s/vLl8e
          labels:
            namespace: sikkerhetstjenesten
            severity: critical