management:
  info:
    git:
      mode: simple
  observations:
    annotations:
      enabled: true
  health:
    group:
      readiness:
        show-components: never
      liveness:
        show-components: never
    redis:
      enabled: false
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring
spring:
  http:
    serviceclient:
      norg:
        base-url: "http://norg2.org"
      graph:
        base-url: "https://graph.microsoft.com/v1.0"
    clients:
      connect-timeout: 3s
      read-timeout: 5s
  threads:
    virtual:
      enabled: true
  application:
    name: entra-proxy
  data:
    redis:
      host: ${valkey.host}
      port: ${valkey.port}
      connect-timeout: 10s
      timeout: 5s
      username: ${valkey.username}
      password: ${valkey.password}
      ssl:
        enabled: true
  cache:
    type: redis
  mvc:
    problemdetails:
      enabled: true
  main:
    banner-mode: off
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-properties: true
  security:
    oauth2:
      client:
        registration:
          graph:
            provider: azuread
            client-id: ${azure.app.client.id}
            client-secret: ${azure.app.client.secret}
            authorization-grant-type: client_credentials
            scope:
              - ${graph.scope}
          norg:
            provider: azuread
            client-id: ${azure.app.client.id}
            client-secret: ${azure.app.client.secret}
            authorization-grant-type: client_credentials

        provider:
          azuread:
            issuer-uri: ${azure.openid.config.issuer}


no.nav.security.jwt:
  issuer:
    azuread:
      discovery-url: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
springdoc:
  swagger-ui:
    oauth:
      client-id: ${azure.app.client.id}
    csrf:
      enabled: true

graph:
  scope: https://graph.microsoft.com/.default
  varighet: 3h

norg:
  varighet: 3h

medlemmer:
    varighet: 3h

entraoid:
  varighet: 365d

valkey:
  username: ${valkey.username.${nais.cluster.cache}}
  password: ${valkey.password.${nais.cluster.cache}}
  uri: ${valkey.uri.${nais.cluster.cache}}
  port: ${valkey.port.${nais.cluster.cache}}
  host: ${valkey.host.${nais.cluster.cache}}
info:
  image: ${nais.app.image:unknown}
