management:
  info:
    git:
      mode: simple
  observations:
    annotations:
      enabled: true
  health:
    group:
      readiness:
        show-components: never
      liveness:
        show-components: never
    redis:
      enabled: false
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: entra-proxy
  data:
    redis:
      host: ${valkey.host}
      port: ${valkey.port}
      connect-timeout: 10s
      timeout: 5s
      username: ${valkey.username}
      password: ${valkey.password}
      ssl:
        enabled: true
  cache:
    type: redis
  mvc:
    problemdetails:
      enabled: true
  main:
    banner-mode: off
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${azure.app.well.known.url}
          audiences: ${azure.app.client.id}
      client:
        provider:
          azuread:
            issuer-uri: ${azure.app.well.known.url}
        registration:
          graph:
            provider: azuread
            authorization-grant-type: client_credentials
            client-id: ${azure.app.client.id}
            client-authentication-method: private_key_jwt
            scope:
              - https://graph.microsoft.com/.default
          norg2:
            provider: azuread
            authorization-grant-type: client_credentials
            client-id: ${azure.app.client.id}
            client-authentication-method: private_key_jwt
            scope:
              - ${graph.scope}
  http:
    serviceclient:
      graph:
        base-url: https://graph.microsoft.com/v1.0
      norg:
        base-url: http://norg2.org

springdoc:
  swagger-ui:
    oauth:
      client-id: ${azure.app.client.id}
    csrf:
      enabled: true

graph:
  scope: https://graph.microsoft.com/.default
  varighet: 3h

norg:
  varighet: 3h

medlemmer:
    varighet: 3h

entraoid:
  varighet: 365d

valkey:
  username: ${valkey.username.${nais.cluster.cache}}
  password: ${valkey.password.${nais.cluster.cache}}
  uri: ${valkey.uri.${nais.cluster.cache}}
  port: ${valkey.port.${nais.cluster.cache}}
  host: ${valkey.host.${nais.cluster.cache}}

info:
  cluster: ${nais.cluster.name:local}
  name: ${spring.application.name}
  image: ${nais.app.image:unknown}
