no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: http://localhost:8080/default/.well-known/openid-configuration
      accepted_audience: client id
  client:
    registration:
      onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id:  client id
          client-jwk: ${azure.app.client.jwk}
          client-auth-method: private_key_jwt
spring:
  cache:
    type: caffeine
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${azure.app.well.known.url}
          audiences: client id
      client:
        provider:
          azuread:
            issuer-uri: ${azure.app.well.known.url}
        registration:
          graph:
            provider: azuread
            authorization-grant-type: client_credentials
            client-id: client id
            client-authentication-method: private_key_jwt
            scope:
              - https://graph.microsoft.com/.default
          norg2:
            provider: azuread
            authorization-grant-type: client_credentials
            client-id: client id
            client-authentication-method: private_key_jwt
            scope:
              - https://graph.microsoft.com/.default
  http:
    serviceclient:
      norg2:
        base-url: http://norg2.org

microsoft:
  graph:
    url: https://graph.microsoft.com/v1.0
    scope: https://graph.microsoft.com/.default