spring:
  security:
    oauth2:
      client:
        registration:
          graph:
            provider: azuread
            client-id: mock-client-id
            client-secret: mock-client-secret
            authorization-grant-type: client_credentials
            scope:
              - https://graph.microsoft.com/.default
          norg:
            provider: azuread
            client-id: mock-client-id
            client-secret: mock-client-secret
            authorization-grant-type: client_credentials
            scope:
              - https://graph.microsoft.com/.default
        provider:
          azuread:
            issuer-uri: https://login.microsoftonline.com/mock-tenant/v2.0

azure:
  app:
    client:
      id: mock-client-id
      secret: mock-client-secret
      jwk: mock-jwk
    well:
      known:
        url: https://login.microsoftonline.com/mock-tenant/v2.0/.well-known/openid-configuration
  openid:
    config:
      issuer: https://login.microsoftonline.com/mock-tenant/v2.0
      token:
        endpoint: https://login.microsoftonline.com/mock-tenant/oauth2/v2.0/token

graph:
  scope: https://graph.microsoft.com/.default