site_name: entra_proxy
docs_dir: adr
site_dir: ../build/reports/pages/adr

theme:
  name: material
  language: "nb"
  palette:
    scheme: default

nav:
  - Oversikt: README.md
  - ADR-001 Synkron fasade: ADR-001-synkron-fasade-for-entra-og-norg.md
  - ADR-002 Cache som lesearkitektur: ADR-002-cache-som-del-av-lesearkitekturen.md
  - ADR-003 Produksjons-API og dev-endepunkter: ADR-003-separasjon-mellom-produksjons-api-og-dev-endepunkter.md
  - ADR-004 Sikkerhetsmodell for OBO og CC: ADR-004-sikkerhetsmodell-for-obo-og-cc.md
  - ADR-005 Resiliens mot Entra og NORG: ADR-005-resiliens-mot-entra-og-norg.md
